// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AgentControllerCreateAlertaData,
  AgentControllerCreateAlertaErrors,
  AgentControllerCreateAlertaResponses,
  AgentControllerCreateMetricaData,
  AgentControllerCreateMetricaErrors,
  AgentControllerCreateMetricaResponses,
  AgentControllerHeartbeatData,
  AgentControllerHeartbeatErrors,
  AgentControllerHeartbeatResponses,
  AlertasControllerFindAllData,
  AlertasControllerFindAllResponses,
  AlertasControllerFindOneData,
  AlertasControllerFindOneErrors,
  AlertasControllerFindOneResponses,
  AlertasControllerUpdateEstadoData,
  AlertasControllerUpdateEstadoErrors,
  AlertasControllerUpdateEstadoResponses,
  AuthControllerLoginData,
  AuthControllerLoginErrors,
  AuthControllerLoginResponses,
  AuthControllerLogoutData,
  AuthControllerLogoutErrors,
  AuthControllerLogoutResponses,
  AuthControllerRefreshData,
  AuthControllerRefreshErrors,
  AuthControllerRefreshResponses,
  AuthControllerRegisterData,
  AuthControllerRegisterErrors,
  AuthControllerRegisterResponses,
  BloqueosControllerCreateData,
  BloqueosControllerCreateErrors,
  BloqueosControllerCreateResponses,
  BloqueosControllerFindAllData,
  BloqueosControllerFindAllResponses,
  BloqueosControllerRemoveData,
  BloqueosControllerRemoveErrors,
  BloqueosControllerRemoveResponses,
  ConfiguracionControllerFindByVpsData,
  ConfiguracionControllerFindByVpsErrors,
  ConfiguracionControllerFindByVpsResponses,
  ConfiguracionControllerUpdateData,
  ConfiguracionControllerUpdateErrors,
  ConfiguracionControllerUpdateResponses,
  HealthControllerCheckData,
  HealthControllerCheckErrors,
  HealthControllerCheckResponses,
  VpsControllerCreateData,
  VpsControllerCreateErrors,
  VpsControllerCreateResponses,
  VpsControllerFindAllData,
  VpsControllerFindAllResponses,
  VpsControllerFindOneData,
  VpsControllerFindOneErrors,
  VpsControllerFindOneResponses,
  VpsControllerGetMetricasData,
  VpsControllerGetMetricasErrors,
  VpsControllerGetMetricasResponses,
  VpsControllerRegenerateTokenData,
  VpsControllerRegenerateTokenErrors,
  VpsControllerRegenerateTokenResponses,
  VpsControllerRemoveData,
  VpsControllerRemoveErrors,
  VpsControllerRemoveResponses,
  WhitelistControllerCreateData,
  WhitelistControllerCreateErrors,
  WhitelistControllerCreateResponses,
  WhitelistControllerFindAllData,
  WhitelistControllerFindAllResponses,
  WhitelistControllerRemoveData,
  WhitelistControllerRemoveErrors,
  WhitelistControllerRemoveResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health check — valida conexión a PostgreSQL
 */
export const healthControllerCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthControllerCheckData, ThrowOnError>,
): RequestResult<HealthControllerCheckResponses, HealthControllerCheckErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    HealthControllerCheckResponses,
    HealthControllerCheckErrors,
    ThrowOnError
  >({ url: '/api/v1/health', ...options });

/**
 * Registrar nuevo usuario
 */
export const authControllerRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRegisterData, ThrowOnError>,
): RequestResult<AuthControllerRegisterResponses, AuthControllerRegisterErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthControllerRegisterResponses,
    AuthControllerRegisterErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Iniciar sesión
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>,
): RequestResult<AuthControllerLoginResponses, AuthControllerLoginErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthControllerLoginResponses,
    AuthControllerLoginErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Renovar tokens (lee refreshToken de la cookie)
 */
export const authControllerRefresh = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRefreshData, ThrowOnError>,
): RequestResult<AuthControllerRefreshResponses, AuthControllerRefreshErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthControllerRefreshResponses,
    AuthControllerRefreshErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/refresh',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Cerrar sesión (revoca refresh token y limpia cookie)
 */
export const authControllerLogout = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLogoutData, ThrowOnError>,
): RequestResult<AuthControllerLogoutResponses, AuthControllerLogoutErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthControllerLogoutResponses,
    AuthControllerLogoutErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/logout',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Listar VPS del usuario autenticado
 */
export const vpsControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<VpsControllerFindAllData, ThrowOnError>,
): RequestResult<VpsControllerFindAllResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<VpsControllerFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/vps',
    ...options,
  });

/**
 * Registrar nuevo VPS — devuelve agentToken una sola vez
 */
export const vpsControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<VpsControllerCreateData, ThrowOnError>,
): RequestResult<VpsControllerCreateResponses, VpsControllerCreateErrors, ThrowOnError> =>
  (options.client ?? client).post<
    VpsControllerCreateResponses,
    VpsControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/vps',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Eliminar VPS (soft delete)
 */
export const vpsControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<VpsControllerRemoveData, ThrowOnError>,
): RequestResult<VpsControllerRemoveResponses, VpsControllerRemoveErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    VpsControllerRemoveResponses,
    VpsControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/vps/{id}',
    ...options,
  });

/**
 * Detalle de un VPS
 */
export const vpsControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<VpsControllerFindOneData, ThrowOnError>,
): RequestResult<VpsControllerFindOneResponses, VpsControllerFindOneErrors, ThrowOnError> =>
  (options.client ?? client).get<
    VpsControllerFindOneResponses,
    VpsControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/vps/{id}',
    ...options,
  });

/**
 * Regenerar agentToken — invalida el anterior, devuelve nuevo token + script
 */
export const vpsControllerRegenerateToken = <ThrowOnError extends boolean = false>(
  options: Options<VpsControllerRegenerateTokenData, ThrowOnError>,
): RequestResult<
  VpsControllerRegenerateTokenResponses,
  VpsControllerRegenerateTokenErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    VpsControllerRegenerateTokenResponses,
    VpsControllerRegenerateTokenErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/vps/{id}/regenerate-token',
    ...options,
  });

/**
 * Métricas históricas del VPS con resumen
 */
export const vpsControllerGetMetricas = <ThrowOnError extends boolean = false>(
  options: Options<VpsControllerGetMetricasData, ThrowOnError>,
): RequestResult<VpsControllerGetMetricasResponses, VpsControllerGetMetricasErrors, ThrowOnError> =>
  (options.client ?? client).get<
    VpsControllerGetMetricasResponses,
    VpsControllerGetMetricasErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/vps/{id}/metricas',
    ...options,
  });

/**
 * Heartbeat del agente — actualiza ultimoHeartbeat y agenteVersion
 */
export const agentControllerHeartbeat = <ThrowOnError extends boolean = false>(
  options: Options<AgentControllerHeartbeatData, ThrowOnError>,
): RequestResult<AgentControllerHeartbeatResponses, AgentControllerHeartbeatErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AgentControllerHeartbeatResponses,
    AgentControllerHeartbeatErrors,
    ThrowOnError
  >({
    url: '/api/v1/agent/heartbeat',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Persiste una métrica del sistema enviada por el agente
 */
export const agentControllerCreateMetrica = <ThrowOnError extends boolean = false>(
  options: Options<AgentControllerCreateMetricaData, ThrowOnError>,
): RequestResult<
  AgentControllerCreateMetricaResponses,
  AgentControllerCreateMetricaErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AgentControllerCreateMetricaResponses,
    AgentControllerCreateMetricaErrors,
    ThrowOnError
  >({
    url: '/api/v1/agent/metricas',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Persiste una alerta de seguridad detectada por el agente
 */
export const agentControllerCreateAlerta = <ThrowOnError extends boolean = false>(
  options: Options<AgentControllerCreateAlertaData, ThrowOnError>,
): RequestResult<
  AgentControllerCreateAlertaResponses,
  AgentControllerCreateAlertaErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AgentControllerCreateAlertaResponses,
    AgentControllerCreateAlertaErrors,
    ThrowOnError
  >({
    url: '/api/v1/agent/alertas',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Historial paginado de bloqueos
 */
export const bloqueosControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<BloqueosControllerFindAllData, ThrowOnError>,
): RequestResult<BloqueosControllerFindAllResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<BloqueosControllerFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/bloqueos',
    ...options,
  });

/**
 * Bloquear IP manualmente desde el dashboard
 */
export const bloqueosControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<BloqueosControllerCreateData, ThrowOnError>,
): RequestResult<BloqueosControllerCreateResponses, BloqueosControllerCreateErrors, ThrowOnError> =>
  (options.client ?? client).post<
    BloqueosControllerCreateResponses,
    BloqueosControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/bloqueos',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Desbloquear IP (por UUID del bloqueo, nunca por IP en la ruta)
 */
export const bloqueosControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<BloqueosControllerRemoveData, ThrowOnError>,
): RequestResult<BloqueosControllerRemoveResponses, BloqueosControllerRemoveErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    BloqueosControllerRemoveResponses,
    BloqueosControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/bloqueos/{id}',
    ...options,
  });

/**
 * Obtener configuración de autonomía de un VPS
 */
export const configuracionControllerFindByVps = <ThrowOnError extends boolean = false>(
  options: Options<ConfiguracionControllerFindByVpsData, ThrowOnError>,
): RequestResult<
  ConfiguracionControllerFindByVpsResponses,
  ConfiguracionControllerFindByVpsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ConfiguracionControllerFindByVpsResponses,
    ConfiguracionControllerFindByVpsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/vps/{id}/configuracion',
    ...options,
  });

/**
 * Actualizar configuración de autonomía de un VPS
 */
export const configuracionControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ConfiguracionControllerUpdateData, ThrowOnError>,
): RequestResult<
  ConfiguracionControllerUpdateResponses,
  ConfiguracionControllerUpdateErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    ConfiguracionControllerUpdateResponses,
    ConfiguracionControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/vps/{id}/configuracion',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Historial paginado de alertas con filtros opcionales
 */
export const alertasControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<AlertasControllerFindAllData, ThrowOnError>,
): RequestResult<AlertasControllerFindAllResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AlertasControllerFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/alertas',
    ...options,
  });

/**
 * Detalle completo de una alerta
 */
export const alertasControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<AlertasControllerFindOneData, ThrowOnError>,
): RequestResult<AlertasControllerFindOneResponses, AlertasControllerFindOneErrors, ThrowOnError> =>
  (options.client ?? client).get<
    AlertasControllerFindOneResponses,
    AlertasControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/alertas/{id}',
    ...options,
  });

/**
 * Actualizar estado de una alerta (revisada/falso positivo/resuelta)
 */
export const alertasControllerUpdateEstado = <ThrowOnError extends boolean = false>(
  options: Options<AlertasControllerUpdateEstadoData, ThrowOnError>,
): RequestResult<
  AlertasControllerUpdateEstadoResponses,
  AlertasControllerUpdateEstadoErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    AlertasControllerUpdateEstadoResponses,
    AlertasControllerUpdateEstadoErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/alertas/{id}/estado',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Listar IPs en whitelist del usuario
 */
export const whitelistControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<WhitelistControllerFindAllData, ThrowOnError>,
): RequestResult<WhitelistControllerFindAllResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<WhitelistControllerFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/whitelist',
    ...options,
  });

/**
 * Agregar IP a la whitelist (nunca se bloquea)
 */
export const whitelistControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<WhitelistControllerCreateData, ThrowOnError>,
): RequestResult<
  WhitelistControllerCreateResponses,
  WhitelistControllerCreateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    WhitelistControllerCreateResponses,
    WhitelistControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/whitelist',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Eliminar IP de la whitelist (por UUID)
 */
export const whitelistControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<WhitelistControllerRemoveData, ThrowOnError>,
): RequestResult<
  WhitelistControllerRemoveResponses,
  WhitelistControllerRemoveErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    WhitelistControllerRemoveResponses,
    WhitelistControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/whitelist/{id}',
    ...options,
  });
