// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type RegisterDto = {
    nombre: string;
    email: string;
    /**
     * Mínimo 8 caracteres, al menos 1 mayúscula, 1 número y 1 símbolo
     */
    password: string;
};

export type LoginDto = {
    email: string;
    password: string;
};

export type RefreshTokenDto = {
    /**
     * Refresh token (opcional si se envía como cookie HttpOnly). La cookie tiene prioridad.
     */
    refreshToken?: string;
};

export type ForgotPasswordDto = {
    email: string;
};

export type ResetPasswordDto = {
    /**
     * Token recibido por email
     */
    token: string;
    password: string;
};

export type CreateVpsDto = {
    nombre: string;
    /**
     * IPv4 o IPv6 del servidor
     */
    ip: string;
    sistemaOperativo: string;
    proveedor: 'DIGITAL_OCEAN' | 'AWS' | 'LINODE' | 'OTRO';
    descripcion?: string;
};

export type HeartbeatDto = {
    agenteVersion?: string;
};

export type CreateMetricaDto = {
    cpuPorcentaje: number;
    ramUsadaMB: number;
    ramTotalMB: number;
    discoUsadaGB: number;
    discoTotalGB: number;
    discoPorcentaje: number;
    requestsPorMinuto: number;
    procesosActivos: number;
    conexionesActivas: number;
    estadoGeneral: 'SEGURO' | 'ADVERTENCIA' | 'BAJO_ATAQUE';
};

export type CreateAlertaDto = {
    tipo: 'BRUTE_FORCE' | 'SQL_INJECTION' | 'HTTP_FLOOD' | 'IP_MALICIOSA' | 'ANOMALIA_PROCESO' | 'ESCANEO_PUERTOS' | 'ESCALACION_DATOS';
    severidad: 'BAJA' | 'MEDIA' | 'ALTA' | 'CRITICA';
    ipOrigen?: string;
    tecnicaMitre?: string;
    paisOrigen?: string;
    descripcionSimple: string;
    descripcionTecnica: string;
    evidencia: {
        [key: string]: unknown;
    };
};

export type CreateBloqueoDto = {
    /**
     * UUID del VPS donde aplicar el bloqueo
     */
    vpsId: string;
    /**
     * IP a bloquear (IPv4 o IPv6)
     */
    ip: string;
    motivo: string;
    /**
     * UUID de la alerta que originó este bloqueo
     */
    alertaId?: string;
};

export type UpdateConfiguracionDto = {
    nivelAutonomia?: 'SOLO_ALERTAR' | 'SUGERIR' | 'GUARDIAN_TOTAL';
    notifEmail?: boolean;
    notifDashboard?: boolean;
    severidadesNotif?: Array<'BAJA' | 'MEDIA' | 'ALTA' | 'CRITICA'>;
    umbralCpuAlerta?: number;
    umbralRamAlerta?: number;
};

export type UpdateEstadoAlertaDto = {
    /**
     * Nuevo estado de la alerta (no se puede volver a DETECTADA manualmente)
     */
    estado: 'REVISADA' | 'FALSO_POSITIVO' | 'RESUELTA';
};

export type CreateWhitelistDto = {
    /**
     * IP a proteger (IPv4 o IPv6, sin CIDR)
     */
    ip: string;
    /**
     * UUID del VPS. Si es null, aplica a todos los VPS del usuario.
     */
    vpsId?: string;
    motivo?: string;
};

export type HealthControllerCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthControllerCheckErrors = {
    /**
     * Base de datos no disponible
     */
    503: {
        status?: string;
        db?: string;
    };
};

export type HealthControllerCheckError = HealthControllerCheckErrors[keyof HealthControllerCheckErrors];

export type HealthControllerCheckResponses = {
    /**
     * Backend y base de datos operativos
     */
    200: {
        status?: string;
        db?: string;
    };
};

export type HealthControllerCheckResponse = HealthControllerCheckResponses[keyof HealthControllerCheckResponses];

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * Datos de entrada inválidos
     */
    400: unknown;
    /**
     * Email ya registrado
     */
    409: unknown;
};

export type AuthControllerRegisterResponses = {
    /**
     * Usuario registrado exitosamente
     */
    201: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Credenciales incorrectas
     */
    401: unknown;
};

export type AuthControllerLoginResponses = {
    /**
     * Login exitoso
     */
    200: unknown;
};

export type AuthControllerRefreshData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type AuthControllerRefreshErrors = {
    /**
     * Token inválido, expirado o reutilizado
     */
    401: unknown;
};

export type AuthControllerRefreshResponses = {
    /**
     * Tokens renovados
     */
    200: unknown;
};

export type AuthControllerLogoutData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthControllerLogoutErrors = {
    /**
     * No autenticado
     */
    401: unknown;
};

export type AuthControllerLogoutResponses = {
    /**
     * Sesión cerrada
     */
    200: unknown;
};

export type AuthControllerForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgot-password';
};

export type AuthControllerForgotPasswordResponses = {
    /**
     * Si el email existe, se envía el enlace
     */
    200: unknown;
};

export type AuthControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type AuthControllerResetPasswordErrors = {
    /**
     * Token inválido o expirado
     */
    400: unknown;
};

export type AuthControllerResetPasswordResponses = {
    /**
     * Contraseña actualizada
     */
    200: unknown;
};

export type VpsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/vps';
};

export type VpsControllerFindAllResponses = {
    /**
     * Lista de VPS
     */
    200: unknown;
};

export type VpsControllerCreateData = {
    body: CreateVpsDto;
    path?: never;
    query?: never;
    url: '/api/v1/vps';
};

export type VpsControllerCreateErrors = {
    /**
     * IP ya registrada para este usuario
     */
    409: unknown;
};

export type VpsControllerCreateResponses = {
    /**
     * VPS creado con token y script
     */
    201: unknown;
};

export type VpsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/vps/{id}';
};

export type VpsControllerRemoveErrors = {
    /**
     * VPS no encontrado
     */
    404: unknown;
};

export type VpsControllerRemoveResponses = {
    /**
     * VPS eliminado
     */
    200: unknown;
};

export type VpsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/vps/{id}';
};

export type VpsControllerFindOneErrors = {
    /**
     * VPS no encontrado
     */
    404: unknown;
};

export type VpsControllerFindOneResponses = {
    /**
     * VPS encontrado
     */
    200: unknown;
};

export type VpsControllerRegenerateTokenData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/vps/{id}/regenerate-token';
};

export type VpsControllerRegenerateTokenErrors = {
    /**
     * VPS no encontrado
     */
    404: unknown;
};

export type VpsControllerRegenerateTokenResponses = {
    /**
     * Token regenerado
     */
    201: unknown;
};

export type VpsControllerGetMetricasData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        /**
         * Período de tiempo para la consulta
         */
        periodo?: '1h' | '24h' | '7d' | '30d';
    };
    url: '/api/v1/vps/{id}/metricas';
};

export type VpsControllerGetMetricasErrors = {
    /**
     * VPS no encontrado
     */
    404: unknown;
};

export type VpsControllerGetMetricasResponses = {
    /**
     * Datos y resumen del período
     */
    200: unknown;
};

export type AgentControllerHeartbeatData = {
    body: HeartbeatDto;
    headers: {
        /**
         * Bearer <agentToken>
         */
        Authorization: string;
        /**
         * UUID del VPS
         */
        'X-Lumi-Vps-Id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/agent/heartbeat';
};

export type AgentControllerHeartbeatErrors = {
    /**
     * Token de agente inválido
     */
    401: unknown;
};

export type AgentControllerHeartbeatResponses = {
    /**
     * Heartbeat registrado
     */
    200: unknown;
};

export type AgentControllerCreateMetricaData = {
    body: CreateMetricaDto;
    headers: {
        /**
         * Bearer <agentToken>
         */
        Authorization: string;
        /**
         * UUID del VPS
         */
        'X-Lumi-Vps-Id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/agent/metricas';
};

export type AgentControllerCreateMetricaErrors = {
    /**
     * Token de agente inválido
     */
    401: unknown;
};

export type AgentControllerCreateMetricaResponses = {
    /**
     * Métrica registrada
     */
    201: unknown;
};

export type AgentControllerCreateAlertaData = {
    body: CreateAlertaDto;
    headers: {
        /**
         * Bearer <agentToken>
         */
        Authorization: string;
        /**
         * UUID del VPS
         */
        'X-Lumi-Vps-Id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/agent/alertas';
};

export type AgentControllerCreateAlertaErrors = {
    /**
     * Token de agente inválido
     */
    401: unknown;
};

export type AgentControllerCreateAlertaResponses = {
    /**
     * Alerta creada con accionTomada según configuración de autonomía
     */
    201: unknown;
};

export type BloqueosControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filtrar por VPS
         */
        vpsId?: string;
        /**
         * Filtrar por IP
         */
        ip?: string;
        estado?: 'BLOQUEADO' | 'DESBLOQUEADO' | 'FALSO_POSITIVO' | 'FALLIDO';
        page?: number;
        limit?: number;
    };
    url: '/api/v1/bloqueos';
};

export type BloqueosControllerFindAllResponses = {
    /**
     * Lista paginada de bloqueos
     */
    200: unknown;
};

export type BloqueosControllerCreateData = {
    body: CreateBloqueoDto;
    path?: never;
    query?: never;
    url: '/api/v1/bloqueos';
};

export type BloqueosControllerCreateErrors = {
    /**
     * VPS no encontrado
     */
    404: unknown;
};

export type BloqueosControllerCreateResponses = {
    /**
     * Bloqueo ejecutado o retornado si ya existía
     */
    201: unknown;
};

export type BloqueosControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/bloqueos/{id}';
};

export type BloqueosControllerRemoveErrors = {
    /**
     * Bloqueo no encontrado o agente no respondió
     */
    404: unknown;
};

export type BloqueosControllerRemoveResponses = {
    /**
     * IP desbloqueada
     */
    200: unknown;
};

export type ConfiguracionControllerFindByVpsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/vps/{id}/configuracion';
};

export type ConfiguracionControllerFindByVpsErrors = {
    /**
     * VPS o configuración no encontrada
     */
    404: unknown;
};

export type ConfiguracionControllerFindByVpsResponses = {
    /**
     * Configuración del VPS
     */
    200: unknown;
};

export type ConfiguracionControllerUpdateData = {
    body: UpdateConfiguracionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/vps/{id}/configuracion';
};

export type ConfiguracionControllerUpdateErrors = {
    /**
     * VPS no encontrado
     */
    404: unknown;
};

export type ConfiguracionControllerUpdateResponses = {
    /**
     * Configuración actualizada
     */
    200: unknown;
};

export type AlertasControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filtrar por VPS
         */
        vpsId?: string;
        tipo?: 'BRUTE_FORCE' | 'SQL_INJECTION' | 'HTTP_FLOOD' | 'IP_MALICIOSA' | 'ANOMALIA_PROCESO' | 'ESCANEO_PUERTOS' | 'ESCALACION_DATOS';
        severidad?: 'BAJA' | 'MEDIA' | 'ALTA' | 'CRITICA';
        estado?: 'DETECTADA' | 'REVISADA' | 'FALSO_POSITIVO' | 'RESUELTA';
        /**
         * Fecha inicio (ISO 8601)
         */
        desde?: string;
        /**
         * Fecha fin (ISO 8601)
         */
        hasta?: string;
        page?: number;
        limit?: number;
    };
    url: '/api/v1/alertas';
};

export type AlertasControllerFindAllResponses = {
    /**
     * Lista paginada de alertas
     */
    200: unknown;
};

export type AlertasControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/alertas/{id}';
};

export type AlertasControllerFindOneErrors = {
    /**
     * Alerta no encontrada
     */
    404: unknown;
};

export type AlertasControllerFindOneResponses = {
    /**
     * Alerta encontrada
     */
    200: unknown;
};

export type AlertasControllerUpdateEstadoData = {
    body: UpdateEstadoAlertaDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/alertas/{id}/estado';
};

export type AlertasControllerUpdateEstadoErrors = {
    /**
     * Alerta no encontrada
     */
    404: unknown;
};

export type AlertasControllerUpdateEstadoResponses = {
    /**
     * Estado actualizado
     */
    200: unknown;
};

export type WhitelistControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filtrar por VPS específico
         */
        vpsId?: string;
    };
    url: '/api/v1/whitelist';
};

export type WhitelistControllerFindAllResponses = {
    /**
     * Lista de IPs protegidas
     */
    200: unknown;
};

export type WhitelistControllerCreateData = {
    body: CreateWhitelistDto;
    path?: never;
    query?: never;
    url: '/api/v1/whitelist';
};

export type WhitelistControllerCreateErrors = {
    /**
     * VPS no encontrado
     */
    404: unknown;
    /**
     * IP ya está en la whitelist
     */
    409: unknown;
};

export type WhitelistControllerCreateResponses = {
    /**
     * IP agregada
     */
    201: unknown;
};

export type WhitelistControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/whitelist/{id}';
};

export type WhitelistControllerRemoveErrors = {
    /**
     * Entrada no encontrada
     */
    404: unknown;
};

export type WhitelistControllerRemoveResponses = {
    /**
     * IP removida
     */
    200: unknown;
};
